# Generated by Django 2.0.1 on 2018-03-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考生姓名')),
                ('name_pinyin', models.CharField(max_length=100, verbose_name='姓名拼音')),
                ('zhengjian_type', models.IntegerField(choices=[(1, '第二代居民身份证'), (0, '请选择证件类型')], default=0, verbose_name='证件类型')),
                ('zhengjian_number', models.IntegerField(verbose_name='证件号码')),
                ('xianyijunren', models.IntegerField(choices=[(1, '否'), (0, '是')], default=0, verbose_name='现役军人')),
                ('minzu', models.IntegerField(choices=[(0, '汉族'), (1, '少数民族')], default=0, verbose_name='考生民族')),
                ('sex', models.IntegerField(choices=[(1, '女'), (0, '男')], default=0, verbose_name='考生性别')),
                ('hunyin', models.IntegerField(choices=[(0, '已婚'), (1, '未婚')], default=0, verbose_name='婚姻状况')),
                ('zhengzhimianmao', models.IntegerField(choices=[(1, '群众'), (4, '无党派人士'), (0, '团员'), (2, '党员'), (3, '预备党员')], default=0, verbose_name='政治面貌')),
                ('address', models.CharField(max_length=500, verbose_name='地址')),
                ('postcode', models.IntegerField(verbose_name='邮政编码')),
                ('fixphone', models.IntegerField(verbose_name='固定电话')),
                ('telephone', models.CharField(max_length=11, verbose_name='移动电话')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='电子信箱')),
                ('laiyuan', models.IntegerField(choices=[(0, '普通全日制应届本科毕业生')], default=0, verbose_name='考生来源')),
                ('graduation_type', models.IntegerField(choices=[(0, '普通全日制')], default=0, verbose_name='取得最后学历的学习形式')),
                ('graduation_time', models.DateTimeField(verbose_name='获得最后学历的毕业年月')),
                ('studentId', models.IntegerField(verbose_name='注册学号')),
                ('graduation_school', models.IntegerField(choices=[(0, '上兰村帝国皇家学院')], default=0, verbose_name='毕业学校')),
                ('graduation_zhuanye', models.IntegerField(choices=[(0, '应用物理')], default=0, verbose_name='毕业专业')),
                ('baokao_type', models.IntegerField(choices=[(0, '非定向就业')], default=0, verbose_name='报考类别')),
                ('nativePlace', models.CharField(max_length=300, verbose_name='考生籍贯')),
                ('registerLocation', models.CharField(max_length=300, verbose_name='户口所在地')),
                ('registerLocationDetail', models.CharField(max_length=300, verbose_name='户口所在地详细地址')),
                ('bornLocation', models.CharField(max_length=300, verbose_name='出生地省市')),
                ('archivesLocation', models.CharField(max_length=300, verbose_name='档案所在地')),
                ('archivesLocationZip', models.IntegerField(verbose_name='考生档案所在单位邮编')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(1, '已删除'), (0, '正常')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '学生',
                'verbose_name': '学生',
            },
        ),
        migrations.CreateModel(
            name='TarGetSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='报考单位名称')),
                ('departmentsName', models.IntegerField(choices=[(0, '大数据学院')], default=0, verbose_name='报考院系的名称')),
                ('professionalName', models.IntegerField(choices=[(0, '计算机科学与技术')], default=0, verbose_name='包括专业名称')),
                ('researchDirection', models.IntegerField(choices=[(0, '人工智能')], default=0, verbose_name='研究方向')),
                ('examCourse', models.IntegerField(choices=[(0, '高等数学')], default=0, verbose_name='考试科目')),
                ('examProvince', models.IntegerField(choices=[(0, '山西省')], default=0, verbose_name='报考点所在省份')),
                ('examSchool', models.IntegerField(choices=[(0, '中北大学')], default=0, verbose_name='报考点')),
            ],
            options={
                'verbose_name_plural': '报考学校',
                'verbose_name': '报考学校',
            },
        ),
    ]
