# Generated by Django 2.0.1 on 2018-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='baokao_type',
            field=models.IntegerField(choices=[(0, '非定向就业'), (1, '定向就业')], default=0, verbose_name='报考类别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='departmentsName',
            field=models.IntegerField(choices=[(2, '软件学院'), (4, '理学院'), (7, '材料科学与工程学院'), (9, '人文社会科学学院'), (8, '机械工程学院'), (5, '艺术学院'), (0, '大数据学院'), (3, '经济与管理学院'), (1, '体育学院'), (6, '仪器与电子学院')], default=0, verbose_name='报考院系的名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='examProvince',
            field=models.IntegerField(choices=[(1, '河南省'), (3, '山东省'), (2, '陕西省'), (0, '山西省'), (4, '河北省')], default=0, verbose_name='报考点所在省份'),
        ),
        migrations.AlterField(
            model_name='student',
            name='examSchool',
            field=models.IntegerField(choices=[(3, '太原理工大学'), (4, '太原工业大学'), (5, '山西师范大学'), (1, '山西财经大学'), (0, '中北大学'), (2, '山西大学'), (6, '太原大学')], default=0, verbose_name='报考点'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_school',
            field=models.IntegerField(choices=[(3, '太原理工大学'), (4, '太原工业大学'), (5, '山西师范大学'), (1, '山西财经大学'), (0, '中北大学'), (2, '山西大学'), (6, '太原大学')], default=0, verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_zhuanye',
            field=models.IntegerField(choices=[(5, '国际经济与贸易'), (3, '软件工程'), (2, '网络工程'), (1, '计算机科学与技术'), (4, '物联网工程'), (0, '应用物理')], default=0, verbose_name='毕业专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hunyin',
            field=models.IntegerField(choices=[(0, '已婚'), (1, '未婚')], default=0, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='student',
            name='professionalName',
            field=models.IntegerField(choices=[(0, '计算机科学与技术'), (4, '数字媒体技术'), (3, '物联网工程'), (5, '数据科学与大数据技术'), (2, '软件工程'), (1, '网络工程')], default=0, verbose_name='报考专业名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='researchDirection',
            field=models.IntegerField(choices=[(2, '大数据与网络安全'), (0, '人工智能'), (3, '大数据与视觉计算'), (1, '虚拟仿真与可视化')], default=0, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengjian_type',
            field=models.IntegerField(choices=[(1, '居民户口簿'), (0, '第二代居民身份证')], default=0, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(0, '团员'), (3, '预备党员'), (4, '无党派人士'), (2, '党员'), (1, '群众')], default=0, verbose_name='政治面貌'),
        ),
    ]
