# Generated by Django 2.0.1 on 2018-03-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarGetSchool',
        ),
        migrations.AddField(
            model_name='student',
            name='departmentsName',
            field=models.IntegerField(choices=[(0, '大数据学院')], default=0, verbose_name='报考院系的名称'),
        ),
        migrations.AddField(
            model_name='student',
            name='examCourse',
            field=models.IntegerField(choices=[(0, '高等数学')], default=0, verbose_name='考试科目'),
        ),
        migrations.AddField(
            model_name='student',
            name='examProvince',
            field=models.IntegerField(choices=[(0, '山西省')], default=0, verbose_name='报考点所在省份'),
        ),
        migrations.AddField(
            model_name='student',
            name='examSchool',
            field=models.IntegerField(choices=[(0, '中北大学')], default=0, verbose_name='报考点'),
        ),
        migrations.AddField(
            model_name='student',
            name='professionalName',
            field=models.IntegerField(choices=[(0, '计算机科学与技术')], default=0, verbose_name='包括专业名称'),
        ),
        migrations.AddField(
            model_name='student',
            name='researchDirection',
            field=models.IntegerField(choices=[(0, '人工智能')], default=0, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minzu',
            field=models.IntegerField(choices=[(1, '少数民族'), (0, '汉族')], default=0, verbose_name='考生民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '已删除')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengjian_type',
            field=models.IntegerField(choices=[(0, '请选择证件类型'), (1, '第二代居民身份证')], default=0, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(4, '无党派人士'), (0, '团员'), (3, '预备党员'), (1, '群众'), (2, '党员')], default=0, verbose_name='政治面貌'),
        ),
    ]
