# Generated by Django 2.0.1 on 2018-03-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0002_auto_20180327_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考生姓名')),
                ('zhengjian_number', models.CharField(max_length=300, verbose_name='证件号码')),
                ('telephone', models.CharField(max_length=11, verbose_name='移动电话')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
            ],
            options={
                'verbose_name': '注册表',
                'verbose_name_plural': '注册表',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='archivesLocationZip',
            field=models.CharField(max_length=300, verbose_name='考生档案所在单位邮编'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fixphone',
            field=models.CharField(max_length=300, verbose_name='固定电话'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hunyin',
            field=models.IntegerField(choices=[(1, '未婚'), (0, '已婚')], default=0, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postcode',
            field=models.CharField(max_length=300, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='考生性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.CharField(max_length=300, verbose_name='注册学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengjian_number',
            field=models.CharField(max_length=300, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(2, '党员'), (3, '预备党员'), (0, '团员'), (4, '无党派人士'), (1, '群众')], default=0, verbose_name='政治面貌'),
        ),
    ]
