# Generated by Django 2.0.1 on 2018-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0003_auto_20180411_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='baokao_school',
            field=models.IntegerField(choices=[(6, '太原大学'), (5, '山西师范大学'), (2, '山西大学'), (3, '太原理工大学'), (1, '山西财经大学'), (4, '太原工业大学'), (0, '中北大学')], default=0, verbose_name='报考学校名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='departmentsName',
            field=models.IntegerField(choices=[(9, '人文社会科学学院'), (1, '体育学院'), (6, '仪器与电子学院'), (5, '艺术学院'), (4, '理学院'), (3, '经济与管理学院'), (0, '大数据学院'), (8, '机械工程学院'), (2, '软件学院'), (7, '材料科学与工程学院')], default=0, verbose_name='报考院系的名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='examProvince',
            field=models.IntegerField(choices=[(1, '河南省'), (4, '河北省'), (2, '陕西省'), (0, '山西省'), (3, '山东省')], default=0, verbose_name='报考点所在省份'),
        ),
        migrations.AlterField(
            model_name='student',
            name='examSchool',
            field=models.IntegerField(choices=[(6, '太原大学'), (5, '山西师范大学'), (2, '山西大学'), (3, '太原理工大学'), (1, '山西财经大学'), (4, '太原工业大学'), (0, '中北大学')], default=0, verbose_name='报考点'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_school',
            field=models.IntegerField(choices=[(6, '太原大学'), (5, '山西师范大学'), (2, '山西大学'), (3, '太原理工大学'), (1, '山西财经大学'), (4, '太原工业大学'), (0, '中北大学')], default=0, verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_zhuanye',
            field=models.IntegerField(choices=[(5, '国际经济与贸易'), (1, '计算机科学与技术'), (3, '软件工程'), (0, '应用物理'), (4, '物联网工程'), (2, '网络工程')], default=0, verbose_name='毕业专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hunyin',
            field=models.IntegerField(choices=[(1, '未婚'), (0, '已婚')], default=0, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minzu',
            field=models.IntegerField(choices=[(0, '汉族'), (1, '少数民族')], default=0, verbose_name='考生民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='professionalName',
            field=models.IntegerField(choices=[(5, '数据科学与大数据技术'), (4, '数字媒体技术'), (2, '软件工程'), (1, '网络工程'), (3, '物联网工程'), (0, '计算机科学与技术')], default=0, verbose_name='报考专业名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='researchDirection',
            field=models.IntegerField(choices=[(3, '大数据与视觉计算'), (2, '大数据与网络安全'), (1, '虚拟仿真与可视化'), (0, '人工智能')], default=0, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xianyijunren',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='现役军人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(2, '党员'), (4, '无党派人士'), (1, '群众'), (3, '预备党员'), (0, '团员')], default=0, verbose_name='政治面貌'),
        ),
    ]
