# Generated by Django 2.0.1 on 2018-03-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0003_auto_20180329_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hunyin',
            field=models.IntegerField(choices=[(0, '已婚'), (1, '未婚')], default=0, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minzu',
            field=models.IntegerField(choices=[(0, '汉族'), (1, '少数民族')], default=0, verbose_name='考生民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xianyijunren',
            field=models.IntegerField(choices=[(0, '是'), (1, '否')], default=0, verbose_name='现役军人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengjian_type',
            field=models.IntegerField(choices=[(1, '第二代居民身份证'), (0, '请选择证件类型')], default=0, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(1, '群众'), (0, '团员'), (2, '党员'), (4, '无党派人士'), (3, '预备党员')], default=0, verbose_name='政治面貌'),
        ),
    ]
