# Generated by Django 2.0.1 on 2018-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0004_auto_20180330_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation_time',
            field=models.DateField(verbose_name='获得最后学历的毕业年月'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minzu',
            field=models.IntegerField(choices=[(1, '少数民族'), (0, '汉族')], default=0, verbose_name='考生民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(0, '团员'), (2, '党员'), (1, '群众'), (4, '无党派人士'), (3, '预备党员')], default=0, verbose_name='政治面貌'),
        ),
    ]
