# Generated by Django 2.0.2 on 2018-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0004_auto_20180330_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, '女'), (0, '男')], default=0, verbose_name='考生性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, '已删除'), (0, '正常')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(1, '群众'), (0, '团员'), (3, '预备党员'), (2, '党员'), (4, '无党派人士')], default=0, verbose_name='政治面貌'),
        ),
    ]
