# Generated by Django 2.0.1 on 2018-04-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0004_auto_20180412_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='baokao_school',
            field=models.IntegerField(choices=[(4, '太原工业大学'), (1, '山西财经大学'), (2, '山西大学'), (5, '山西师范大学'), (6, '太原大学'), (3, '太原理工大学'), (0, '中北大学')], default=0, verbose_name='报考学校名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='baokao_type',
            field=models.IntegerField(choices=[(0, '非定向就业'), (1, '定向就业')], default=0, verbose_name='报考类别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='departmentsName',
            field=models.IntegerField(choices=[(1, '体育学院'), (9, '人文社会科学学院'), (3, '经济与管理学院'), (5, '艺术学院'), (6, '仪器与电子学院'), (8, '机械工程学院'), (0, '大数据学院'), (4, '理学院'), (7, '材料科学与工程学院'), (2, '软件学院')], default=0, verbose_name='报考院系的名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='examProvince',
            field=models.IntegerField(choices=[(3, '山东省'), (1, '河南省'), (0, '山西省'), (2, '陕西省'), (4, '河北省')], default=0, verbose_name='报考点所在省份'),
        ),
        migrations.AlterField(
            model_name='student',
            name='examSchool',
            field=models.IntegerField(choices=[(4, '太原工业大学'), (1, '山西财经大学'), (2, '山西大学'), (5, '山西师范大学'), (6, '太原大学'), (3, '太原理工大学'), (0, '中北大学')], default=0, verbose_name='报考点'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_school',
            field=models.IntegerField(choices=[(4, '太原工业大学'), (1, '山西财经大学'), (2, '山西大学'), (5, '山西师范大学'), (6, '太原大学'), (3, '太原理工大学'), (0, '中北大学')], default=0, verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_zhuanye',
            field=models.IntegerField(choices=[(5, '国际经济与贸易'), (3, '软件工程'), (1, '计算机科学与技术'), (2, '网络工程'), (4, '物联网工程'), (0, '应用物理')], default=0, verbose_name='毕业专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='laiyuan',
            field=models.IntegerField(choices=[(1, '普通全日制往届本科毕业生'), (0, '普通全日制应届本科毕业生')], default=0, verbose_name='考生来源'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minzu',
            field=models.IntegerField(choices=[(1, '少数民族'), (0, '汉族')], default=0, verbose_name='考生民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='professionalName',
            field=models.IntegerField(choices=[(5, '数据科学与大数据技术'), (3, '物联网工程'), (2, '软件工程'), (0, '计算机科学与技术'), (4, '数字媒体技术'), (1, '网络工程')], default=0, verbose_name='报考专业名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='researchDirection',
            field=models.IntegerField(choices=[(1, '虚拟仿真与可视化'), (0, '人工智能'), (2, '大数据与网络安全'), (3, '大数据与视觉计算')], default=0, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '已删除')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xianyijunren',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='现役军人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengjian_type',
            field=models.IntegerField(choices=[(1, '居民户口簿'), (0, '第二代居民身份证')], default=0, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(0, '团员'), (4, '无党派人士'), (1, '群众'), (3, '预备党员'), (2, '党员')], default=0, verbose_name='政治面貌'),
        ),
    ]
