# Generated by Django 2.0.1 on 2018-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0005_auto_20180401_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='minzu',
            field=models.IntegerField(choices=[(0, '汉族'), (1, '少数民族')], default=0, verbose_name='考生民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xianyijunren',
            field=models.IntegerField(choices=[(1, '否'), (0, '是')], default=0, verbose_name='现役军人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(4, '无党派人士'), (0, '团员'), (1, '群众'), (3, '预备党员'), (2, '党员')], default=0, verbose_name='政治面貌'),
        ),
    ]
