# Generated by Django 2.0.2 on 2018-04-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0005_auto_20180330_1247'),
        ('bo', '0006_auto_20180402_1008'),
    ]

    operations = [
    ]
